// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSc7noYXWSgn1_wspRVbTHYFlnxo87CX8',
    appId: '1:919419641844:android:af9f0822e4e636f7cfa3a1',
    messagingSenderId: '919419641844',
    projectId: 'eschool-mobile-fe51a',
    storageBucket: 'eschool-mobile-fe51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRN3G7Ioba5FsZr2uvXiGhRmO-kt3_p0',
    appId: '1:919419641844:ios:9c471bcd0c9f29c4cfa3a1',
    messagingSenderId: '919419641844',
    projectId: 'eschool-mobile-fe51a',
    storageBucket: 'eschool-mobile-fe51a.firebasestorage.app',
    iosBundleId: 'id.ac.eschool.teacherstaff.android',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvr-wq4sN06e29jTOH2KnX7NovckpFzGA',
    appId: '1:919419641844:web:68560c16468ce9d9cfa3a1',
    messagingSenderId: '919419641844',
    projectId: 'eschool-mobile-fe51a',
    authDomain: 'eschool-mobile-fe51a.firebaseapp.com',
    storageBucket: 'eschool-mobile-fe51a.firebasestorage.app',
    measurementId: 'G-T9CCYR2E87',
  );
}
